const x = 10;

try{
    x = 3
}catch(err){
    console.log(`Error: ${err}`)
}